### ISSUE TITLE
Can't make library (Error in Doxyfile)

### ISSUE THREAD

**Issue by feldim2425** [jdkoftinoff/jdksmidi#14]
Can't compile library.
Error in the Doxyfile. Output: http://pastebin.com/U2DXJfKV
I used the same commands as in the wiki.

**Comment by jdkoftinoff** [comment]
Which version of doxygen are you using? I am using 1.8.8 and it does not give any errors.

**Comment by feldim2425** [comment]
I updated doxygen to 1.8.6 and now it's working.
