### ISSUE TITLE
is there a note on/off callback/notifier with note pitch

### ISSUE THREAD

**Issue by rsp4jack** [jdkoftinoff/jdksmidi#21]
I am writing a MIDI player.

Now it needs to display **which** notes is on or off (Not consider hold pedal), so I have to use a callback or notifier to tell the program there is a note on/off event and **its note pitch**.

All in all, I need a callback/notifier to notify the program the note event and **its pitch**.
And I can't find it. `MIDISequencerGUIEventNotifier` does not notify the note's pitch.

So, where is it?

**Comment by jdkoftinoff** [comment]
Hi! Sorry it's been a long time. Perhaps look at https://github.com/jdkoftinoff/jdksmidi/blob/master/examples/jdksmidi_test_sequencer.cpp#L134
as an example

**Comment by rsp4jack** [comment]
Does it works with AdvancedSequencer?

**Comment by rsp4jack** [comment]
I find a solution: Inherit a MIDIProcessor and call `MIDIDriver::SetOutProcessor` which driver do you use.
